"""Descrição da migração

Revision ID: ec17feda5f9e
Revises: 
Create Date: 2024-09-19 02:48:25.856810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec17feda5f9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(length=11),
               type_=mysql.VARCHAR(length=14),
               existing_nullable=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_unique_constraint(None, 'clients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.alter_column('clients', 'phone',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
